version: "3.1"

services:
  db:
    image: cynide/custom-db-musicbrainz
    networks: 
      - musicbrainz
      
  server:
    build:
      context: ./server
      dockerfile: dockerfile
    volumes:
      - "server-data:/musicbrainz-server"
    networks:
      - musicbrainz
    ports:
      - "5000:5000"
    depends_on: 
      - db
      - redis

  redis:
    image: redis:alpine
    restart: unless-stopped
    networks: 
      - musicbrainz
    expose:
      - "6379"


networks: 
  musicbrainz:
volumes:
  server-data: